### ISSUE TITLE
App crashes when scrolling through drinks filtered by ingredient.

### ISSUE THREAD

**Issue by SeriouslyAwesome** [jmduke/Barback#174]
Seems to happen pretty consistently regardless of ingredient.

Flow: Open app > Tap on "Ingredients" tab > Tap on any ingredient > Begin scrolling through the list of recipes > App quits.

iPhone 6, iOS 8.2 (12D508)

**Comment by jmduke** [comment]
Ah, yeah, this was due to an index out of bounds ( -_- ) hitting Bartender's Choice, since that's a faux recipe that doesn't have any actual ingredients.  It's been [fixed](https://github.com/jmduke/Barback/commit/655c340013f0680ec39119a16161b4697cea3496), but I'm not 100% sure that it went out in the last crop of bugfixes.  Can you share what version you're on?

**Comment by SeriouslyAwesome** [comment]
v2.3.1

**Comment by jmduke** [comment]
With the rewrite of the search controller and the move away from using `Bartender's Choice` as a faux recipe to just a `tableFooterView` in https://github.com/jmduke/Barback/commit/6b60ebe3372e8709846b1da32dc835bbaa130c69, this has been fixed:

![screen shot 2015-04-15 at 10 12 58 am](https://cloud.githubusercontent.com/assets/461046/7164880/4abe05b6-e358-11e4-90b7-8647526925c8.png)

Closing -- thanks again for bringing this up!

**Comment by SeriouslyAwesome** [comment]
Great!
